# Generated by Django 4.0.3 on 2023-04-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_status_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerVO',
        ),
        migrations.AddField(
            model_name='appointment',
            name='vip_status',
            field=models.BooleanField(default=False),
        ),
    ]
