# Generated by Django 4.0.3 on 2023-04-26 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_appointment_vin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('appt_date_time',)},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appt_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appt_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 12, 29, 13, 465704, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
