# Generated by Django 4.0.3 on 2023-04-26 17:39

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('appt_date', 'appt_time')},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appt_date_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 26, 17, 38, 51, 645870, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
