# Generated by Django 4.0.3 on 2023-04-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='service_rest.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CANCELED', 'Canceled'), ('FINISHED', 'Finished')], default='CREATED', max_length=10),
        ),
    ]
