# Generated by Django 4.0.3 on 2023-04-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_alter_appointment_status_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CANCELED', 'Canceled'), ('FINISHED', 'Finished')], default='CREATED', max_length=10, null=True),
        ),
    ]
