# Generated by Django 4.0.3 on 2023-04-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_alter_status_id_alter_status_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='CREATED', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
