# Generated by Django 4.0.3 on 2023-05-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0002_automobile_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedPriceVO',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='automobile',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automobiles', to='inventory_rest.suggestedpricevo'),
        ),
    ]
